on:
  push:
    branches:
      - main

jobs:
  caprover-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup NodeJS and Caprover
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"

      - name: Deploy to Caprover
        env:
          CAPROVER_BRANCH: main
          CAPROVER_APP: ${{ secrets.CAPROVER_APP }}
          CAPROVER_URL: ${{ secrets.CAPROVER_URL }}
          CAPROVER_NAME: ${{ secrets.CAPROVER_NAME }}
          CAPROVER_APP_TOKEN: ${{ secrets.CAPROVER_TOKEN }} # Use a secret for Caprover token
        run: |
          npm install -g caprover
          caprover deploy
